version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - tourdata:/var/lib/postgresql/data
      - ./dbinit.sh:/init.sh:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tourdb

volumes:
  tourdata: